[build]
  publish = "simple-build"
  command = "echo 'No build required - static site'"

[build.environment]
  NODE_VERSION = "18"

# APIリダイレクト設定（バックエンドデプロイ後に有効化）
[[redirects]]
  from = "/api/*"
  to = "https://your-backend-url.com/api/:splat"
  status = 200
  force = true

# SPAルーティング（必要に応じて）
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# セキュリティヘッダー
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"

# キャッシュ設定
[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# 開発環境用の環境変数（Netlify管理画面で設定）
[context.production.environment]
  REACT_APP_API_URL = "https://your-production-backend.com"

[context.deploy-preview.environment]
  REACT_APP_API_URL = "https://your-staging-backend.com"

[context.branch-deploy.environment]
  REACT_APP_API_URL = "https://your-development-backend.com"