services:
  - type: web
    name: autocad-translator-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
    disk:
      name: uploads
      mountPath: /opt/render/project/src/uploads
      sizeGB: 1